Precidiendo Spam de Youtube con Python, utilizando pandas y sklearn, la idea es convertir palabras en vectores para usar como caracteristicas para ayudar en la clasificación

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
import matplotlib as plt
import seaborn as sns

In [5]:
df1 = pd.read_csv("Youtube01-Psy.csv")

In [6]:
df1.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [7]:
df2 = pd.read_csv("Youtube02-KatyPerry.csv")
df3 = pd.read_csv("Youtube03-LMFAO.csv")
df4 = pd.read_csv("Youtube04-Eminem.csv")
df5 = pd.read_csv("Youtube05-Shakira.csv")

In [8]:
frames = [df1,df2,df3,df4,df5]

In [10]:
#Concatenamos o hacemos un merge de los conjuntos de datos
df_merged = pd.concat(frames)

In [11]:
df_merged

COMMENT_ID                AUTHOR  \
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU             Julius NM   
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A           adam riyati   
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8      Evgeny Murashkin   
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04       ElNino Melendez   
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw                GsMega   
..                                           ...                   ...   
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA          Katie Mettam   
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  Sabina Pearson-Smith   
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs         jeffrey jules   
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0        Aishlin Maciel   
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA           Latin Bosch   

                           DATE  \
0           2013-11-07T06:20:48   
1           2013-11-07T12:37:15   
2           2013-11-08T17:34:21   
3           2013-11-09T08:28:43   
4           2013-11-10T16:05:38   
..                          ...   
365  2013-07-13T13:27:39.441000   
366  2013-07-13T13:14:30.021000   
367  2013-07-13T12:09:31.188000   
368  2013-07-13T11:17:52.308000   
369  2013-07-12T22:33:27.916000   

                                               CONTENT  CLASS  
0    Huh, anyway check out this you[tube] channel: ...      1  
1    Hey guys check out my new channel and our firs...      1  
2               just for test I have to say murdev.com      1  
3     me shaking my sexy ass on my channel enjoy ^_^       1  
4              watch?v=vtaRGgvGtWQ   Check this out .      1  
..                                                 ...    ...  
365  I love this song because we sing it at Camp al...      0  
366  I love this song for two reasons: 1.it is abou...      0  
367                                                wow      0  
368                            Shakira u are so wiredo      0  
369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

In [12]:
# Tamaño Total
df_merged.shape

(1956, 5)

In [13]:
# Merging con llaves
keys = ["Psy","KatyPerry","LMFAO","Eminem","Shakira"]

In [14]:
df_with_keys = pd.concat(frames,keys=keys)

In [15]:
df_with_keys

COMMENT_ID  \
Psy     0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU   
        1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A   
        2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8   
        3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04   
        4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw   
...                                                  ...   
Shakira 365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA   
        366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI   
        367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs   
        368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0   
        369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA   

                           AUTHOR                        DATE  \
Psy     0               Julius NM         2013-11-07T06:20:48   
        1             adam riyati         2013-11-07T12:37:15   
        2        Evgeny Murashkin         2013-11-08T17:34:21   
        3         ElNino Melendez         2013-11-09T08:28:43   
        4                  GsMega         2013-11-10T16:05:38   
...                           ...                         ...   
Shakira 365          Katie Mettam  2013-07-13T13:27:39.441000   
        366  Sabina Pearson-Smith  2013-07-13T13:14:30.021000   
        367         jeffrey jules  2013-07-13T12:09:31.188000   
        368        Aishlin Maciel  2013-07-13T11:17:52.308000   
        369           Latin Bosch  2013-07-12T22:33:27.916000   

                                                       CONTENT  CLASS  
Psy     0    Huh, anyway check out this you[tube] channel: ...      1  
        1    Hey guys check out my new channel and our firs...      1  
        2               just for test I have to say murdev.com      1  
        3     me shaking my sexy ass on my channel enjoy ^_^       1  
        4              watch?v=vtaRGgvGtWQ   Check this out .      1  
...                                                        ...    ...  
Shakira 365  I love this song because we sing it at Camp al...      0  
        366  I love this song for two reasons: 1.it is abou...      0  
        367                                                wow      0  
        368                            Shakira u are so wiredo      0  
        369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

In [16]:
# Validamos solo comentarios de shakira
df_with_keys.loc['Shakira']

COMMENT_ID  \
0            z13lgffb5w3ddx1ul22qy1wxspy5cpkz504   
1              z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj   
2          z12quxxp2vutflkxv04cihggzt2azl34pms0k   
3              z12icv3ysqvlwth2c23eddlykyqut5z1h   
4              z133stly3kete3tly22petvwdpmghrlli   
..                                           ...   
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA   
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI   
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs   
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0   
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA   

                                 AUTHOR                        DATE  \
0                            dharma pal  2015-05-29T02:30:18.971000   
1                         Tiza Arellano  2015-05-29T00:14:48.748000   
2    Prìñçeśś Âliś Łøvê Dømíñø Mâđiś™   2015-05-28T21:00:08.607000   
3                         Eric Gonzalez  2015-05-28T20:47:12.193000   
4                         Analena López  2015-05-28T17:08:29.827000   
..                                  ...                         ...   
365                        Katie Mettam  2013-07-13T13:27:39.441000   
366                Sabina Pearson-Smith  2013-07-13T13:14:30.021000   
367                       jeffrey jules  2013-07-13T12:09:31.188000   
368                      Aishlin Maciel  2013-07-13T11:17:52.308000   
369                         Latin Bosch  2013-07-12T22:33:27.916000   

                                               CONTENT  CLASS  
0                                           Nice song      0  
1                                        I love song       0  
2                                        I love song       0  
3    860,000,000 lets make it first female to reach...      0  
4                        shakira is best for worldcup      0  
..                                                 ...    ...  
365  I love this song because we sing it at Camp al...      0  
366  I love this song for two reasons: 1.it is abou...      0  
367                                                wow      0  
368                            Shakira u are so wiredo      0  
369                         Shakira is the best dancer      0  

[370 rows x 5 columns]

In [17]:
# Guardamos y escribimos los conjuntos de datos concatenados en un archivos csv
df_with_keys.to_csv("YoutubeSpamMergeddata.csv")

In [18]:

df = df_with_keys

In [19]:
df.size


9780

Limpieza de Datos

In [20]:
# Checamos los nombres de las columnas
df.columns

Index(['COMMENT_ID', 'AUTHOR', 'DATE', 'CONTENT', 'CLASS'], dtype='object')

In [21]:
# Checamos los tipos de datos
df.dtypes

COMMENT_ID    object
AUTHOR        object
DATE          object
CONTENT       object
CLASS          int64
dtype: object

In [22]:
# Validamos los datos nulos 
df.isnull().isnull().sum()

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [23]:
# Validamos las fechas
df["DATE"]

Psy      0             2013-11-07T06:20:48
         1             2013-11-07T12:37:15
         2             2013-11-08T17:34:21
         3             2013-11-09T08:28:43
         4             2013-11-10T16:05:38
                           ...            
Shakira  365    2013-07-13T13:27:39.441000
         366    2013-07-13T13:14:30.021000
         367    2013-07-13T12:09:31.188000
         368    2013-07-13T11:17:52.308000
         369    2013-07-12T22:33:27.916000
Name: DATE, Length: 1956, dtype: object

In [24]:
df.AUTHOR
# si quieres convertir el nombre del autor en primer nombr y apellido usa la instrucción comentada
#df[["FIRSTNAME","LASTNAME"]] = df['AUTHOR'].str.split(expand=True)

Psy      0                 Julius NM
         1               adam riyati
         2          Evgeny Murashkin
         3           ElNino Melendez
         4                    GsMega
                        ...         
Shakira  365            Katie Mettam
         366    Sabina Pearson-Smith
         367           jeffrey jules
         368          Aishlin Maciel
         369             Latin Bosch
Name: AUTHOR, Length: 1956, dtype: object

Trabajando con el contenido del texto

In [25]:
df_data = df[["CONTENT","CLASS"]]

In [26]:
df_data.columns

Index(['CONTENT', 'CLASS'], dtype='object')

In [27]:
df_x = df_data["CONTENT"]
df_y = df_data["CLASS"]

Extracción de Caracteristicas del texto
CountVectorizer
TfidfVectorizer

In [28]:
cv = CountVectorizer()
ex = cv.fit_transform(["Great song but check this out","What is this song?"])

In [29]:
ex.toarray()

array([[1, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=int64)

In [31]:
cv.get_feature_names_out()

array(['but', 'check', 'great', 'is', 'out', 'song', 'this', 'what'],
      dtype=object)

In [32]:
#extraemos las caracteristicas con CountVectorizer
corpus = df_x
cv = CountVectorizer()
X = cv.fit_transform(corpus) #limpiamos los datos

In [33]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
#tomamos los nombres de las caracteristicas
cv.get_feature_names_out()

array(['00', '000', '002', ..., 'ｔｈｉｓ', 'ｕｓｒ', 'ｗｗｗ'], dtype=object)

Construcción del Modelo

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, df_y, test_size=0.33, random_state=42)

In [37]:
X_train

<1310x4454 sparse matrix of type '<class 'numpy.int64'>'
	with 17525 stored elements in Compressed Sparse Row format>

In [38]:
#Clasificador Naive Bayes
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9195046439628483

In [39]:
#Rendimiento del modelo
print("Rendimiento del modelo", clf.score(X_test, y_test)*100, "%")

Rendimiento del modelo 91.95046439628483 %


In [40]:
#prección con nuestro modelo
clf.predict(X_test)

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,

In [41]:
#ejemplo de predicción
comment = ["Check this out"]
vect = cv.transform(comment).toarray()

In [42]:
clf.predict(vect)

array([1], dtype=int64)

In [43]:
class_dict = {'ham':0, 'spam':1}

In [44]:
class_dict.values()

dict_values([0, 1])

In [45]:
if clf.predict(vect) == 1:
    print("Spam")
else:
    print("no spam")

Spam


In [46]:
#ejemplo de predicción 2
comment1 = ["Great song friend"]
vect = cv.transform(comment1).toarray()
clf.predict(vect)

array([0], dtype=int64)

Guardando el modelo


In [47]:
import pickle

In [48]:
naivebayesML = open("YtbSpam_model.pkl","wb")

In [49]:
pickle.dump(clf, naivebayesML)

In [50]:
naivebayesML.close()

In [52]:
#carga el modelo
ytb_model = open("YtbSpam_model.pkl","rb")
new_model = pickle.load(ytb_model)
new_model

MultinomialNB()

In [53]:
# Sample Prediciton 3
comment2 = ["Hey Music Fans I really appreciate all of you,but see this song too"]
vect = cv.transform(comment2).toarray()
new_model.predict(vect)

array([1], dtype=int64)

In [54]:
if new_model.predict(vect) == 1:
    print("Spam")
else:
    print("Ham")

Spam
